#!/usr/bin/env node
//
// Generates src/version.ts from the "version" field in package.json.
//
// The plugin version is needed at runtime (update check + telemetry metadata),
// but restating it in source lets it drift behind package.json. Deriving it from
// the single source of truth here makes that class of bug structurally impossible.
//
// Run automatically as part of `build` and the release script; it can also be
// invoked directly with `npm run generate:version`.

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const pkgPath = join(root, "package.json");
const outPath = join(root, "src", "version.ts");

const pkg = JSON.parse(readFileSync(pkgPath, "utf-8"));
const version = pkg.version;

if (typeof version !== "string" || !version.trim()) {
  console.error("sync-version: package.json has no valid \"version\" field");
  process.exit(1);
}

const contents = `// AUTO-GENERATED by scripts/sync-version.mjs — do not edit by hand.
// Sourced from package.json "version" so the two cannot drift.
export const PLUGIN_VERSION = ${JSON.stringify(version)};
`;

const existing = (() => {
  try {
    return readFileSync(outPath, "utf-8");
  } catch {
    return null;
  }
})();

if (existing !== contents) {
  writeFileSync(outPath, contents);
  console.log(`sync-version: wrote src/version.ts (PLUGIN_VERSION = ${version})`);
} else {
  console.log(`sync-version: src/version.ts already up to date (${version})`);
}
